# Generated by Django 5.2.9 on 2025-12-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff_member', models.BooleanField(default=False)),
                ('user_profile_image', models.ImageField(blank=True, default=None, null=True, upload_to='User Profiles')),
                ('verification_token', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('verification_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_two_factor_authentication_enabled', models.BooleanField(default=False)),
                ('two_factor_pin', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
