# Generated by Django 5.2.9 on 2025-12-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_loginattempt_otpverifyattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff_member',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_two_factor_authentication_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_pin',
        ),
        migrations.AddField(
            model_name='user',
            name='user_plan',
            field=models.CharField(blank=True, default='free', max_length=25, null=True),
        ),
    ]
