# Generated by Django 5.2.9 on 2025-12-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_is_staff_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_plan',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
