# Generated by Django 5.2.9 on 2025-12-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_two_factor_authentication_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
